export const pageContent = {
  English: {
    enter: "Enter",
    hintsOn: "Show Hints",
    hintsOff: "Hide Hints",
    skip: "Skip",
    correct: "Correct:",
    incorrect: "Incorrect:",
    twotries: "2 tries remaining",
    onetry: "1 try remaining",
    quit: "Quit Review",
  },
  Korean: {
    enter: "확인하기",
    hintsOn: "힌트 보이기",
    hintsOff: "힌트 숨기기",
    skip: "건너뛰기",
    correct: "정답:",
    incorrect: "오답:",
    twotries: "남은 시도 2번",
    onetry: "남은 시도 1번",
    quit: "그만두기",
  },
  Japanese: {
    enter: "確認する",
    hintsOn: "ヒントを見せる",
    hintsOff: "ヒントを隠す",
    skip: "スキップ",
    correct: "正解:",
    incorrect: "誤答:",
    twotries: "残りの試み2回",
    onetry: "残りの試み1回",
    quit: "やめる",
  },
};
