export const pageContent = {
  English: {
    editTitle: "Editing Card",
    newCardTitle: "New Card",
    error: "Card already in deck.",
    frontLabel: "Front",
    backLabel: "Back",
    meaning: "Meaning: ",
    searching: "Searching for Definition...",
    noDef: "No definition found.",
    upButton: "Up",
    resetButton: "Reset",
    removeButton: "Remove Image",
    downButton: "Down",
    zoomOutButton: "Zoom-Out",
    hint: "Hint ",
    example: "E.g.",
    swapButton: "Swap Inputs",
    imageType1: "Definition",
    imageType2: "General",
    saveButton: "Save",
    addButton: "Add New Card",
    cancelButton: "Cancel",
    exitButton: "Exit",
  },
  Korean: {
    editTitle: "카드 수정",
    newCardTitle: "새 카드 만들기",
    error: "카드가 이미 데크에 있습니다.",
    frontLabel: "앞면",
    backLabel: "뒷면",
    meaning: "뜻: ",
    searching: "뜻 찾는 중...",
    noDef: "뜻이 없음.",
    upButton: "위",
    resetButton: "초기화",
    removeButton: "이미지 제거",
    downButton: "아래",
    zoomOutButton: "축소",
    hint: "힌트 ",
    example: "예문",
    swapButton: "카드 앞뒤 바꾸기",
    imageType1: "뜻",
    imageType2: "일반",
    saveButton: "저장",
    addButton: "새 카드 추가",
    cancelButton: "취소",
    exitButton: "닫기",
  },
  Japanese: {
    editTitle: "カード修正",
    newCardTitle: "新しいカード作り",
    error: "カードはすでにデッキにあります。",
    frontLabel: "前面",
    backLabel: "裏面",
    meaning: "意味: ",
    searching: "意味を探し中···",
    noDef: "意味が無い.",
    upButton: "上",
    resetButton: "初期化",
    removeButton: "画像除去",
    downButton: "下",
    zoomOutButton: "縮小",
    hint: "ヒント: ",
    example: "例文",
    swapButton: "カードの前後に入れ替える",
    imageType1: "意味",
    imageType2: "一般",
    saveButton: "セーブ",
    addButton: "新しいカード追加",
    cancelButton: "キャンセル",
    exitButton: "閉じる",
  },
};
