export const pageContent = {
  English: {
    title: "Browse Deck",
    total: "Total Cards: ",
    front: "Front",
    back: "Back",
    hint: "Hint",
    image: "Image",
    nextReview: "Next Review",
    level: "Level",
    createdDate: "Created",
    tools: "Tools",
    edit: "Edit",
    del: "Delete",
    delConfirm: "Are you sure you want to delete this card?",
    noCards: "No cards yet!",
    import: "Import / Upload",
    home: "Home",
    delDeck: "Delete Deck",
    delDeckConfirm: "Are you sure you want to delete your deck?",
    delDeckDoubleCheck:
      "Are you REALLY sure you want to DELETE your DECK? (Consider uploading your deck first)",
  },
  Korean: {
    title: "데크 보기",
    total: "총 카드 수: ",
    front: "앞면",
    back: "뒷면",
    hint: "힌트",
    image: "이미지",
    nextReview: "다음 복습",
    level: "레벨",
    createdDate: "만든 날짜",
    tools: "도구",
    edit: "수정",
    del: "삭제",
    delConfirm: "이 카드를 삭제하시겠습니까?",
    noCards: "아직 카드가 없네요!",
    import: "가져오기 / 업로드",
    home: "홈페이지",
    delDeck: "데크 삭제",
    delDeckConfirm: "데크를 삭제하시겠습니까?",
    delDeckDoubleCheck:
      "정말로 데크를 삭제하시겠습니까? (먼저 업로드하는 것을 고려하십시오)",
  },
  Japanese: {
    title: "デッキ·ビュー",
    total: "カード総数: ",
    front: "前面",
    back: "裏面",
    hint: "ヒント",
    image: "イメージ",
    nextReview: "次の復習",
    level: "レベル",
    createdDate: "作成日時",
    tools: "道具",
    edit: "修整",
    del: "削除",
    delConfirm: "このカードを削除しますか？",
    noCards: "まだカードがないですね！",
    import: "インポート / アップロード",
    home: "ホームページ",
    delDeck: "デッキ削除",
    delDeckConfirm: "デッキを削除しますか？",
    delDeckDoubleCheck:
      "本当にデッキを削除しますか？ （先にアップロードすることを考慮してください。）",
  },
};
