export const pageContent = {
  English: {
    title: "Import / Upload Cards",
    deckName: "Deck Name",
    deckPassword: "Deck Password",
    hide: "Hide",
    show: "Show",
    import: "Import",
    upload: "Upload",
    uploadedDecks: "Uploaded Decks",
    cardNumber: "Card Number",
    password: "Password",
    del: "Delete",
    done: "Done",
    checkImport: "Are you sure you want to import?",
    checkExport: "Are you sure you want to export?",
    overwrite: "Overwrite current upload?",
    badPassword: "Incorrect Password!",
    uploadSuccess: "Deck uploaded successfully to Firebase",
    errorSend: "Error sending data to Firebase:",
    badDetails: "There is no deck that matches those details.",
    errorRetrieve: "Error retrieving data from Firebase:",
    delDeck: "Are you sure you want to delete this deck?",
    delFail: "Failed to delete deck",
    delError: "Error deleting deck:",
    noNew: "No new cards!",
    newCards: "There are",
    newCards2: "new cards. Add to current deck?",
    addedCards: "New cards added to deck.",
  },
  Korean: {
    title: "카드 불러오기 / 업로드",
    deckName: "데크 이름",
    deckPassword: "데크 비밀번호",
    hide: "숨기기",
    show: "보이기",
    import: "불러오기",
    upload: "업로드",
    uploadedDecks: "업로드된 데크",
    cardNumber: "카드 수",
    password: "비밀번호",
    del: "삭제",
    done: "완료",
    checkImport: "데크를 불러오시겠습니까?",
    checkExport: "데크를 업로드하시겠습니까?",
    overwrite: "현재 업로드 덮어쓰시겠습니까?",
    badPassword: "비밀번호 틀렸습니다!",
    uploadSuccess: "데크가 파이어베이스에 성공적으로 업로드되었습니다",
    errorSend: "파이어베이스로 데이터를 보내는 중 오류가 발생했습니다:",
    badDetails: "입력하신 정보과 일치하는 데크가 없습니다.",
    errorRetrieve: "파이어베이스에서 데이터를 가져오는 중 오류가 발생했습니다:",
    delDeck: "이 데크를 삭제하시겠습니까?",
    delFail: "데크를 삭제하지 못했습니다",
    delError: "데크 삭제 중 오류 발생:",
    noNew: "새 카드가 없습니다!",
    newCards: "새 카드",
    newCards2: "개가 있습니다. 현재 데크에 추가하시겠습니까?",
    addedCards: "새로운 카드가 추가되었습니다.",
  },
  Japanese: {
    title: "Import / Upload Cards",
    deckName: "Deck Name",
    deckPassword: "Deck Password",
    hide: "Hide",
    show: "Show",
    import: "Import",
    upload: "Upload",
    uploadedDecks: "Uploaded Decks",
    cardNumber: "Card Number",
    password: "Password",
    del: "Delete",
    done: "Done",
    checkImport: "Are you sure you want to ",
    checkImport2: "?",
    overwrite: "Overwrite current upload?",
    badPassword: "Incorrect Password!",
    uploadSuccess: "Deck uploaded successfully to Firebase",
    errorSend: "Error sending data to Firebase:",
    badDetails: "There is no deck that matches those details.",
    errorRetrieve: "Error retrieving data from Firebase:",
    delDeck: "Are you sure you want to delete this deck?",
    delFail: "Failed to delete deck",
    delError: "Error deleting deck:",
    noNew: "No new cards!",
    newCards: "There are ",
    newCards2: " new cards. Add to current deck?",
    addedCards: "New cards added to deck.",
  },
};
