export const pageContent = {
  English: {
    title: "Settings",
    displayLabel: "Display Language:",
    langButtonLabel: "English",
    oddLabel: "Swap question and answer on odd card levels",
    switchOff: "OFF",
    switchSwap: "Swap",
    shortcuts: "Keyboard Shortcuts:",
    hint: "Hint Toggle:",
    skip: "Skip Card:",
    save: "Save",
  },
  Korean: {
    title: "설정",
    displayLabel: "표시 언어:",
    langButtonLabel: "한국어",
    oddLabel: "홀수 카드 레벨로 질문과 답변을 맞바꾸기",
    switchOff: "끄기",
    switchSwap: "바꾸기",
    shortcuts: "단축키:",
    hint: "힌트 전환:",
    skip: "카드 건너뛰기:",
    save: "저장",
  },
  Japanese: {
    title: "設定",
    displayLabel: "表示言語:",
    langButtonLabel: "日本語",
    oddLabel: "奇数カードレベルで質問と回答を交換する",
    switchOff: "OFF",
    switchSwap: "交換する",
    shortcuts: "キーボードショートカット:",
    hint: "ヒント切り替え:",
    skip: "カードをスキップ:",
    save: "保存",
  },
};
